#!/usr/bin/env fish

set -e
. ../../nvm.sh

# Remove the stuff we're clobbering.
test -e ../../v0.6.14; and rm -R ../../v0.6.14

# Install
nvm install 0.6.14

# Check
test -d ../../v0.6.14
nvm run v0.6.14 --version | grep v0.6.14
